// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockStorage is a mock of Storage interface
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// IsRegistered mocks base method
func (m *MockStorage) IsRegistered(ctx context.Context, owner string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRegistered", ctx, owner)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRegistered indicates an expected call of IsRegistered
func (mr *MockStorageMockRecorder) IsRegistered(ctx, owner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRegistered", reflect.TypeOf((*MockStorage)(nil).IsRegistered), ctx, owner)
}

// CreateRequest mocks base method
func (m *MockStorage) CreateRequest(ctx context.Context, owner, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRequest", ctx, owner, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateRequest indicates an expected call of CreateRequest
func (mr *MockStorageMockRecorder) CreateRequest(ctx, owner, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRequest", reflect.TypeOf((*MockStorage)(nil).CreateRequest), ctx, owner, code)
}

// CheckRequest mocks base method
func (m *MockStorage) CheckRequest(ctx context.Context, owner, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRequest", ctx, owner, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckRequest indicates an expected call of CheckRequest
func (mr *MockStorageMockRecorder) CheckRequest(ctx, owner, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRequest", reflect.TypeOf((*MockStorage)(nil).CheckRequest), ctx, owner, code)
}

// MarkRequestProcessed mocks base method
func (m *MockStorage) MarkRequestProcessed(ctx context.Context, owner string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRequestProcessed", ctx, owner)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRequestProcessed indicates an expected call of MarkRequestProcessed
func (mr *MockStorageMockRecorder) MarkRequestProcessed(ctx, owner interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRequestProcessed", reflect.TypeOf((*MockStorage)(nil).MarkRequestProcessed), ctx, owner)
}
