// Code generated by MockGen. DO NOT EDIT.
// Source: sender.go

// Package mail is a generated GoMock package.
package mail

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockSender is a mock of Sender interface
type MockSender struct {
	ctrl     *gomock.Controller
	recorder *MockSenderMockRecorder
}

// MockSenderMockRecorder is the mock recorder for MockSender
type MockSenderMockRecorder struct {
	mock *MockSender
}

// NewMockSender creates a new mock instance
func NewMockSender(ctrl *gomock.Controller) *MockSender {
	mock := &MockSender{ctrl: ctrl}
	mock.recorder = &MockSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockSender) EXPECT() *MockSenderMockRecorder {
	return m.recorder
}

// SendVerificationEmail mocks base method
func (m *MockSender) SendVerificationEmail(ctx context.Context, email, owner, code string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationEmail", ctx, email, owner, code)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationEmail indicates an expected call of SendVerificationEmail
func (mr *MockSenderMockRecorder) SendVerificationEmail(ctx, email, owner, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationEmail", reflect.TypeOf((*MockSender)(nil).SendVerificationEmail), ctx, email, owner, code)
}

// SendWelcomeEmailAsync mocks base method
func (m *MockSender) SendWelcomeEmailAsync(ctx context.Context, email string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendWelcomeEmailAsync", ctx, email)
}

// SendWelcomeEmailAsync indicates an expected call of SendWelcomeEmailAsync
func (mr *MockSenderMockRecorder) SendWelcomeEmailAsync(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWelcomeEmailAsync", reflect.TypeOf((*MockSender)(nil).SendWelcomeEmailAsync), ctx, email)
}
