CREATE TABLE request (
    owner VARCHAR NOT NULL UNIQUE,
    address VARCHAR NOT NULL UNIQUE,
    code VARCHAR NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    confirmed_at TIMESTAMP WITHOUT TIME ZONE
);