version: '2.2'

networks:
  decentr-cerberus:
    name: decentr-cerberus
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.231.0/24
          gateway: 172.16.231.1

services:
  vulcan:
    # use this image for local image
    # image: cerberus-local:latest
    image: decentr/cerberus
    container_name: decentr-vulcan
    restart: always
    environment:
      - "HTTP_HOST=0.0.0.0"
      - "HTTP_PORT=7070"
      - "LOG_LEVEL=debug"
    networks:
      - decentr-cerberus
    ports:
      - "70800:7070"
